import { describe, expect, it } from "vitest";
import { argon2Hash } from "../app/tools/hasher.web";

/**
 * Cross-implementation parity for the web/desktop password hash.
 *
 * `argon2Hash` output IS the credential sent to /users/authenticate — the server re-hashes it and compares
 * against the stored ServerHash. So if this build's hash differs from the native app's by one byte, every
 * account fails to log in on desktop with an indistinguishable 400. That is exactly what happened once:
 * hasher.web.ts fed argon2 the ASCII bytes of the salt's HEX STRING rather than the bytes that string
 * encodes, and desktop login returned "Username/password is incorrect."
 *
 * The expected values below are GROUND TRUTH generated by the server's own C# implementation
 * (Shuffull.Shared.Tools.Hasher.Argon2Hash, Konscious.Security.Cryptography.Argon2id) at the same
 * parameters — m=2^14, t=5, p=4, 16-byte output, salt = UTF-8 bytes of "ShuffullSaltingSixteenBytesLong!".
 * Three independent implementations agree on them: Konscious (C#), hash-wasm (here), and the native
 * Android module, which hex-DECODES the salt string hasher.ts hex-encodes and so arrives at the same bytes.
 *
 * If this test fails, do not update the expected values — the hash changed, and that logs everyone out.
 */
describe("argon2Hash web/native parity", () => {
    // [input, expected] — from the C# server implementation.
    const VECTORS: [string, string][] = [
        ["hello", "d96c56f4aa8e9b723a9f82f65b84c9ad"],
        ["testuser;testpass", "d89d3ed20daa8e436e5ab413772503d0"],
    ];

    it.each(VECTORS)("matches the C# implementation for %j", async (input, expected) => {
        expect(await argon2Hash(input)).toBe(expected);
    });
});
