export const STORAGE_KEYS = {
    HOST_ADDRESS: "HOST_ADDRESS",
    CURRENT_USER_ID: "CURRENT_USER_ID",
    FOREGROUND_TIMER_ID: "FOREGROUND_TIMER_ID",
    CURRENT_SONG_FILTERS: "CURRENT_SONG_FILTERS",
}