export const STORAGE_KEYS = {
    HOST_ADDRESS: "HOST_ADDRESS",
    CURRENT_USER_ID: "CURRENT_USER_ID",
    FOREGROUND_TIMER_GUID: "FOREGROUND_TIMER_GUID",
    CURRENT_SONG_FILTERS: "CURRENT_SONG_FILTERS",
}